baseURL: "https://dataviz.andrewheiss.com/"
languageCode: en-us
title: Data visualization
theme: ath-tufte-hugo
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Reference
      url: /reference/
      weight: 4
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Andrew Heiss
  thumbnail: /images/dataviz_meta.png
  course:
    number: MPA 635
    instructor: Dr. Andrew Heiss
    instructorURL: "https://www.andrewheiss.com"
    instructorTwitter: andrewheiss
    instructorGitHub: andrewheiss
    email: andrew_heiss@byu.edu
    semester: Fall 2017
    days: Tuesday
    time: "4:00–7:00 PM"
    location: Somewhere
    dates: "September 4–October XX, 2017"
  university: 
    name: Brigham Young University
    url: "https://www.byu.edu"
  school:
    name: Romney Institute of Public Management
    url: "https://marriottschool.byu.edu/mpa/"
  description: A website built through Hugo and blogdown.
  primaryColor: "#A5452B"
  secondaryColor: "#ECAD49"
  logo:
    url: /images/dataviz_hires.png
    alt: Data visualization
  meta:
    twitterSite: "@andrewheiss"
    twitterCreator: "@andrewheiss"
    fbAuthor: "https://www.facebook.com/andrewheiss"
